name: 🚀 Deploy to Shared Hosting via FTP (Alternative)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "FTP Server: ${{ secrets.FTP_SERVER }}"
          echo "FTP Username: ${{ secrets.FTP_USERNAME }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deployment/xeddo/
          server-dir: /xeddo/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
